/*
 * Copyright 2015 Loic Merckel
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package lh.api.showcase.shared;

import java.util.HashSet;
import java.util.Set;

public enum AirportCode {
	
	AAL, AAR, ABE, ABJ, ABK, ABQ, ABV, ABZ, ACA, ACC, ACE, ACK, ACT, ACV, 
	ACY, ADA, ADB, ADD, ADF, ADK, ADL, ADQ, ADZ, AES, AEX, AGH, AGP, AGT, AGU, 
	AHB, AIA, AJL, AJU, AKJ, AKL, ALA, ALB, ALF, ALG, ALS, ALW, AMA, AMD, AMH, 
	AMI, AMM, AMS, ANC, ANF, ANU, AOI, AOK, AOR, APL, ARI, ARN, ARW, ASB, ASE, 
	ASM, ASO, ASR, ASU, ASW, ATH, ATL, ATQ, ATW, AUA, AUH, AUS, AUW, AVL, AVP, 
	AXD, AXM, AXT, AXU, AYT, BAH, BAQ, BAV, BBA, BBI, BBK, BBO, BCN, BDL, BDQ, 
	BEG, BEL, BEN, BET, BEW, BEY, BFF, BFL, BFM, BFN, BGA, BGF, BGI, BGO, BGR, 
	BGW, BGY, BHM, BHO, BHX, BHY, BIA, BIL, BIO, BIS, BJL, BJM, BJR, BJV, BJX, 
	BKI, BKK, BKO, BLA, BLL, BLQ, BLR, BLZ, BNA, BNE, BOG, BOI, BOJ, BOM, BOO, 
	BOS, BPN, BPS, BPT, BRC, BRE, BRI, BRM, BRO, BRS, BRU, BRW, BSB, BSL, BTR, 
	BTU, BTV, BUD, BUF, BUQ, BUR, BWI, BWN, BZE, BZN, BZV, CAE, CAG, CAI, CAK, 
	CAN, CBR, CCJ, CCP, CCS, CCU, CDG, CDR, CDV, CEB, CEC, CEI, CEZ, CFU, CGB, 
	CGH, CGK, CGN, CGO, CGQ, CGR, CHA, CHC, CHO, CHQ, CHS, CIC, CID, CJB, CJC, 
	CJU, CKB, CKG, CKY, CLD, CLE, CLJ, CLL, CLO, CLT, CMB, CME, CMH, CMN, CMX, 
	CND, CNF, CNS, CNX, CNY, COD, COK, COO, COR, COS, CPH, CPO, CPR, CPT, CRD, 
	CRP, CRW, CSL, CSX, CTA, CTG, CTS, CTU, CUC, CUL, CUM, CUN, CUR, CUU, CVG, 
	CWB, CYS, CZM, CZX, DAB, DAC, DAR, DAT, DAX, DAY, DBV, DCA, DDC, DDG, DEL, 
	DEN, DFW, DGO, DIB, DIK, DIR, DKR, DLA, DLC, DLH, DLM, DME, DMM, DMU, DNK, 
	DOH, DOK, DPS, DRO, DRS, DRT, DRW, DSM, DSN, DTM, DTN, DTW, DUB, DUR, DUS, 
	DVL, DVO, DXB, DYG, EAR, EAT, EAU, EBB, EBJ, EBL, EDI, EFL, EGE, ELM, ELP, 
	ELS, EMA, ERI, ESB, EUG, EVE, EVN, EWN, EWR, EYW, EZE, FAO, FAR, FAT, FAY, 
	FBM, FCA, FCO, FDH, FIH, FKB, FKS, FLL, FLN, FLO, FLR, FMM, FMN, FMO, FMY, 
	FNA, FNC, FOC, FOE, FOR, FRA, FRS, FSD, FSZ, FTE, FUE, FUK, FWA, FYV, GAU, 
	GAY, GBE, GCC, GCK, GDE, GDL, GDN, GDQ, GEG, GIG, GJT, GLA, GMB, GMP, GNV, 
	GOA, GOI, GOJ, GOT, GPT, GRB, GRI, GRJ, GRR, GRU, GRZ, GSO, GSP, GTF, GUA, 
	GUC, GUM, GVA, GWL, GWT, GYD, GYE, GYN, GZT, HAC, HAJ, HAK, HAM, HAN, HAR, 
	HAU, HAV, HBA, HBE, HDF, HDN, HDS, HDY, HEL, HER, HET, HFE, HGH, HHH, HIJ, 
	HIL, HIN, HKD, HKG, HKT, HLD, HLH, HMO, HND, HNL, HOG, HOV, HPN, HRB, HRE, 
	HRG, HRK, HRL, HSG, HSV, HTS, HUE, HUX, HYD, HYN, HYS, IAD, IAH, IAS, IBZ, 
	ICN, ICT, IDR, IGD, IGR, IGU, IKA, ILE, ILM, IMF, INC, IND, INN, IOA, IOS, 
	IPL, IQQ, ISG, ISN, IST, ITH, ITM, ITO, IWJ, IWK, IXA, IXB, IXC, IXD, IXE, 
	IXJ, IXL, IXM, IXR, IXS, IXU, IXZ, JAC, JAI, JAN, JAX, JDH, JDZ, JED, JER, 
	JFK, JGA, JHB, JHM, JIB, JIJ, JIM, JJN, JKH, JLR, JMK, JMS, JMU, JNB, JOI, 
	JRH, JRO, JSI, JTR, JUB, KBP, KBR, KBV, KCH, KCM, KCZ, KEF, KGL, KGS, KHH, 
	KHN, KIJ, KIM, KIV, KIX, KKC, KKJ, KKN, KLR, KLU, KLX, KMG, KMI, KMJ, KMQ, 
	KNU, KOA, KOJ, KOK, KPO, KRK, KRN, KRR, KRS, KRT, KSC, KSD, KSU, KTM, KTN, 
	KTT, KTW, KUA, KUF, KUH, KUL, KUO, KVA, KWE, KWI, KWJ, KWL, LAD, LAN, LAP, 
	LAR, LAS, LAX, LBB, LBF, LBJ, LBL, LBU, LBV, LCA, LCH, LCJ, LCY, LDB, LED, 
	LEJ, LEX, LFT, LFW, LGA, LGB, LGK, LHR, LHW, LIH, LIM, LIN, LIR, LIS, LIT, 
	LJU, LKO, LLA, LLI, LLW, LMP, LNK, LNY, LNZ, LOS, LPA, LPB, LPI, LPQ, LPT, 
	LRD, LSC, LSP, LST, LUN, LUX, LUZ, LVI, LWO, LWS, LXN, LXR, LYH, LYI, LYR, 
	LYS, LZH, MAA, MAD, MAF, MAH, MAN, MAO, MAR, MBA, MBE, MBJ, MBS, MCI, MCK, 
	MCO, MCT, MCZ, MDC, MDE, MDL, MDT, MDZ, MEL, MEM, MES, MEX, MFE, MFR, MGA, 
	MGM, MGW, MHT, MIA, MID, MIG, MJM, MJT, MKC, MKG, MKK, MLA, MLB, MLE, MLH, 
	MLI, MLM, MLU, MMB, MMX, MNL, MOB, MOD, MOL, MPL, MPM, MQX, MRD, MRS, MRU, 
	MRY, MSN, MSO, MSP, MSQ, MSU, MSY, MTJ, MTS, MTT, MTY, MUB, MUC, MUN, MVD, 
	MWH, MWX, MXP, MYE, MYJ, MYR, MYY, MZL, MZT, NAG, NAP, NAT, NBE, NBO, NCE, 
	NCL, NDG, NDJ, NGB, NGO, NGS, NIM, NKG, NLA, NLP, NNG, NOC, NOU, NQN, NQY, 
	NRT, NSI, NST, NTE, NTG, NTQ, NUE, NVT, OAJ, OAK, OAX, OBO, ODS, OGG, OIM, 
	OIT, OKA, OKC, OKJ, OLB, OMA, OME, ONJ, ONT, OOL, OPO, ORD, ORF, OSD, OSL, 
	OTP, OTZ, OUA, OUL, OXB, OXR, PAD, PAH, PAT, PBC, PBI, PDP, PDX, PEG, PEI, 
	PEK, PEN, PER, PEW, PGA, PGV, PHC, PHF, PHL, PHW, PHX, PIA, PIR, PIT, PKB, 
	PKU, PLM, PLZ, PMC, PMI, PMO, PMV, PNH, PNL, PNQ, PNR, PNS, PNT, POA, POL, 
	POZ, PPT, PRG, PRN, PSA, PSC, PSG, PSP, PTG, PTY, PUB, PUJ, PUQ, PUS, PUW, 
	PUY, PVD, PVG, PVH, PVR, PWM, PZB, PZO, QDU, QKL, QKU, QRO, RAI, RAJ, RAK, 
	RAO, RAP, RAR, RCB, RDD, RDM, RDU, REC, REL, REP, RES, RGN, RHO, RIC, RIW, 
	RIX, RJK, RKS, RLG, RNB, RNO, ROA, ROB, ROC, ROV, RPR, RSU, RSW, RTB, RTM, 
	RUH, RZE, SAC, SAH, SAL, SAN, SAP, SAT, SAV, SAW, SBA, SBN, SBP, SBW, SBY, 
	SBZ, SCC, SCE, SCL, SCN, SDF, SDJ, SDK, SDL, SDQ, SDU, SEA, SEZ, SFO, SFT, 
	SGF, SGN, SGU, SHB, SHC, SHE, SHJ, SHL, SHR, SHV, SIA, SIN, SIT, SJC, SJD, 
	SJJ, SJO, SJP, SJU, SKG, SKP, SLA, SLC, SLP, SLW, SLZ, SMF, SMI, SMR, SMX, 
	SNA, SNN, SNU, SOC, SOF, SPC, SPI, SPU, SRQ, SRZ, SSA, SSG, SSH, STL, STN, 
	STR, STS, STT, STV, SUB, SUF, SUN, SVG, SVZ, SWA, SXB, SXR, SYD, SYO, SYR, 
	SYX, SZG, SZX, TAB, TAE, TAK, TAM, TAO, TBS, TBZ, TDX, TET, TEZ, TFS, TGD, 
	TGG, TGO, TGU, TGZ, THE, THS, TIA, TIJ, TIP, TIR, TIV, TKS, TKU, TLH, TLL, 
	TLS, TLV, TMP, TNA, TNR, TOP, TOS, TOY, TPA, TPE, TRC, TRD, TRF, TRI, TRN, 
	TRS, TRV, TRZ, TSE, TSJ, TSN, TSR, TTJ, TUC, TUL, TUN, TUS, TVC, TWU, TXG, 
	TXL, TXN, TYN, TYR, TYS, TZX, UBJ, UBP, UDI, UDR, UIO, UKB, UME, UPG, URC, 
	URT, USH, USM, USN, UTH, UTN, UTT, UVF, VAA, VAR, VCE, VCT, VEL, VER, VFA, 
	VGO, VIE, VIX, VKO, VLC, VLN, VNO, VNS, VNX, VOL, VPS, VRA, VRN, VSA, VTE, 
	VTZ, WAW, WDH, WEH, WKJ, WLG, WNZ, WRG, WRL, WRO, WUH, WUX, WVB, WXN, XER, 
	XFN, XIL, XIY, XMN, XNA, XNN, XRY, XUZ, YAK, YAM, YAO, YBC, YBG, YBL, YCD, 
	YCG, YCU, YDF, YEG, YFB, YFC, YGJ, YGK, YGP, YGR, YHZ, YIH, YKA, YKM, YLW, 
	YMM, YNJ, YNT, YNZ, YOW, YPR, YQB, YQG, YQL, YQM, YQQ, YQR, YQT, YQU, YQX, 
	YQY, YQZ, YSB, YSJ, YTS, YUL, YUY, YVO, YVR, YWG, YWK, YWL, YXC, YXE, YXH, 
	YXJ, YXS, YXT, YXU, YXX, YXY, YYB, YYC, YYD, YYF, YYG, YYJ, YYR, YYT, YYY, 
	YYZ, YZF, YZP, YZR, YZV, ZAD, ZAG, ZAL, ZBF, ZCL, ZCO, ZDH, ZIH, ZLO, ZNZ, 
	ZOS, ZPC, ZQN, ZRH, ZTH, ZUH, ZWS ; 
	
	
	public static Set<String> toStringSet () {
		final Set<String>  set = new HashSet<String>();
		for (AirportCode ac : values ()){
			set.add(ac.toString());
		}
		return set ;
	}
}
