/*
 * Copyright 2015 Loic Merckel
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package lh.api.showcase.shared;

import java.util.HashSet;
import java.util.Set;

public enum CityCodeGL {

	GAA,GAB,GAC,GAD,GAE,GAF,GAG,GAH,GAI,GAJ,GAK,GAL,GAM,GAO,GAP,GAQ,GAR,GAS,GAT,GAU,GAV,GAW,GAX,GAY,GAZ,GBA,GBB,GBC,GBD,GBE,GBF,GBG,GBH,GBI,GBJ,GBK,GBL,GBM,GBP,GBR,GBS,GBU,GBV,GBZ,GCA,GCC,GCI,GCK,GCM,GCN,GCY,GDA,GDD,GDE,GDG,GDH,GDI,GDJ,GDL,GDM,GDN,GDO,GDP,GDQ,GDT,GDV,GDW,GDX,GDZ,GEB,GEC,GED,GEE,
	GEF,GEG,GEI,GEK,GEL,GEO,GER,GES,GET,GEV,GEW,GEX,GEY,GFB,GFD,GFE,GFF,GFK,GFL,GFN,GFO,GFR,GFY,GGC,GGD,GGE,GGG,GGL,GGN,GGO,GGR,GGS,GGT,GGW,GHA,GHB,GHC,GHD,GHE,GHK,GHM,GHN,GHT,GHU,GIB,GIC,GID,GIF,GII,GIL,GIM,GIR,GIS,GIT,GIY,GIZ,GJA,GJL,GJM,GJR,GJT,GKA,GKE,GKH,GKL,GKN,GKO,GKT,GLA,GLC,GLD,GLE,GLF,GLG,GLH,GLI,GLK,GLL,GLM,GLN,GLO,GLP,GLQ,GLR,GLS,GLT,GLV,GLW,GLX,GLY,GLZ,GMA,GMB,GMC,GME,GMI,GMM,GMN,GMR,GMT,
	GMY,GNA,GNB,GND,GNE,GNG,GNI,GNM,GNN,GNR,GNS,GNT,GNU,GNV,GNZ,GOA,GOB,GOC,GOE,GOH,GOI,GOJ,GOK,GOL,GOM,GON,GOO,GOP,GOQ,GOR,GOS,GOT,GOU,GOV,GOW,GOY,GOZ,GPA,GPB,GPI,GPL,GPN,GPO,GPS,GPT,GPZ,GQJ,GQQ,GRA,GRB,GRC,GRD,GRE,GRG,GRH,GRI,GRJ,GRL,GRM,GRN,GRO,GRP,GRQ,GRR,GRS,GRT,GRV,GRW,GRX,GRY,GRZ,GSA,GSB,GSC,GSH,GSI,GSN,GSO,GSP,GSR,GSS,GST,GSU,GTA,GTB,GTC,GTE,GTF,GTG,GTI,GTK,GTO,GTS,GTT,GTW,GTY,GUA,GUB,GUC,GUD,
	GUE,GUF,GUG,GUH,GUI,GUJ,GUL,GUM,GUO,GUP,GUQ,GUR,GUS,GUT,GUU,GUV,GUW,GUX,GUY,GVA,GVE,GVI,GVL,GVP,GVR,GVT,GVW,GVX,GWA,GWD,GWE,GWL,GWN,GWO,GWS,GWT,GWV,GWY,GXF,GXG,GXQ,GXX,GXY,GYA,GYE,GYI,GYL,GYM,GYN,GYP,GYR,GZI,GZM,GZO,GZT,HAA,HAB,HAC,HAD,HAE,HAF,HAG,HAI,HAJ,HAK,HAL,HAM,HAN,HAO,HAP,HAR,HAS,HAT,HAU,HAV,HAW,HAY,HAZ,HBA,HBC,HBG,HBH,HBI,HBL,HBN,HBO,HBR,HBT,HBX,HCA,HCB,HCC,HCM,HCQ,HCR,HCW,HDA,HDB,HDD,HDE,
	HDF,HDH,HDM,HDN,HDS,HDY,HEA,HEB,HED,HEE,HEH,HEI,HEK,HEL,HEN,HEO,HER,HES,HET,HEZ,HFA,HFD,HFE,HFF,HFN,HFS,HFT,HGA,HGD,HGH,HGL,HGN,HGO,HGR,HGT,HGU,HGZ,HHA,HHE,HHH,HHI,HHN,HHQ,HHR,HHZ,HIB,HID,HIE,HIG,HIH,HII,HIJ,HIL,HIN,HIO,HIP,HIR,HIS,HIT,HIW,HIX,HJR,HJT,HKB,HKD,HKG,HKK,HKN,HKT,HKV,HKY,HLA,HLB,HLC,HLD,HLF,HLG,HLH,HLI,HLJ,HLL,HLM,HLN,HLS,HLT,HLU,HLV,HLW,HLY,HLZ,HME,HMG,HMI,HMJ,HMO,HMR,HMS,HMT,HMV,HNA,
	HNB,HNC,HNE,HNG,HNH,HNI,HNK,HNL,HNM,HNN,HNO,HNS,HNX,HNY,HOA,HOB,HOC,HOD,HOE,HOF,HOG,HOH,HOI,HOK,HOL,HOM,HON,HOO,HOP,HOQ,HOR,HOS,HOT,HOU,HOV,HOW,HOX,HOY,HPA,HPB,HPE,HPH,HPN,HPT,HPY,HQM,HRA,HRB,HRE,HRG,HRJ,HRK,HRL,HRM,HRN,HRO,HRR,HRS,HRY,HSB,HSC,HSG,HSI,HSL,HSM,HSP,HSS,HST,HSV,HTA,HTB,HTF,HTG,HTH,HTI,HTL,HTN,HTO,HTR,HTS,HTU,HTV,HTW,HTY,HTZ,HUB,HUC,HUD,HUE,HUF,HUG,HUH,HUI,HUJ,HUK,HUL,HUM,HUN,HUQ,HUS,
	HUT,HUU,HUV,HUX,HUY,HUZ,HVA,HVB,HVD,HVE,HVG,HVK,HVM,HVN,HVR,HVS,HWA,HWD,HWI,HWK,HWN,HWO,HXX,HYA,HYC,HYD,HYF,HYG,HYL,HYN,HYR,HYS,HYV,HZB,HZG,HZK,HZL,HZV,
	IAA,IAG,IAM,IAN,IAQ,IAR,IAS,IAU,IBA,IBE,IBI,IBO,IBP,IBZ,ICA,ICI,ICK,ICL,ICO,ICR,ICT,ICY,IDA,IDB,IDF,IDG,IDI,IDK,IDN,IDO,IDP,IDR,IDY,IEG,IEJ,IEV,IFA,IFF,IFJ,IFL,IFN,IFO,IFP,IGA,IGB,IGD,IGE,IGG,IGH,IGM,IGN,IGO,IGR,IGU,IHA,IHN,IHO,IHU,IIA,IIN,IIS,IJK,
	IJU,IJX,IKB,IKI,IKK,IKL,IKO,IKP,IKS,IKT,ILA,ILB,ILC,ILE,ILF,ILG,ILH,ILI,ILK,ILL,ILM,ILN,ILO,ILP,ILR,ILU,ILX,ILY,ILZ,IMA,IMB,IMD,IMF,IMG,IMI,IMK,IML,IMM,IMN,IMO,IMP,IMT,IMZ,INA,INB,INC,IND,INE,INF,ING,INH,INI,INJ,INK,INL,INM,INN,INO,INQ,INS,INT,INU,INV,INW,INX,INY,INZ,IOA,IOK,IOM,ION,IOP,IOR,IOS,IOU,IOW,IPA,IPC,IPE,IPG,IPH,IPI,IPL,IPN,IPT,IPU,IPW,IQM,IQN,IQQ,IQT,IRA,IRB,IRC,IRD,IRE,IRG,IRI,IRJ,IRK,
	IRN,IRO,IRP,IRS,ISA,ISB,ISC,ISD,ISG,ISH,ISI,ISJ,ISK,ISL,ISM,ISN,ISO,ISP,ISQ,ISS,IST,ISU,ISW,ITA,ITB,ITE,ITH,ITI,ITK,ITN,ITO,ITQ,IUE,IUL,IUM,IUS,IVA,IVC,IVG,IVH,IVL,IVO,IVR,IVW,IWA,IWD,IWJ,IWK,IWO,IXA,IXB,IXC,IXD,IXE,IXG,IXH,IXI,IXJ,IXK,IXL,IXM,IXN,IXP,IXQ,IXR,IXS,IXT,IXU,IXV,IXW,IXY,IXZ,IYK,IZM,IZO,IZT,JAA,JAB,JAC,JAD,JAF,JAG,JAH,JAI,JAK,JAL,JAM,JAN,JAQ,JAS,JAT,JAU,JAV,JAX,JBK,JBR,JBS,JCB,JCH,JCK,
	JCM,JCN,JCR,JCT,JCY,JDA,JDF,JDH,JDN,JDO,JDY,JDZ,JED,JEE,JEF,JEG,JEJ,JEM,JEQ,JER,JEV,JFM,JFN,JFR,JGA,JGB,JGE,JGN,JGO,JGR,JHB,JHG,JHM,JHQ,JHS,JHW,JIA,JIB,JIJ,JIL,JIM,JIN,JIP,JIR,JIU,JIW,JJI,JJN,JJU,JKG,JKH,JKR,JKT,JKV,JLA,JLD,JLH,JLN,JLO,JLP,JLR,JLS,JMB,JMC,JMH,JMK,JMO,JMS,JMU,JNA,JNB,JNG,JNI,JNN,JNP,JNS,JNU,JNX,JNZ,JOE,JOG,JOH,JOI,JOK,JOL,JOM,JON,JOP,JOR,JOS,JOT,JPA,JPD,JPR,JQE,JRH,JRK,JRN,JRO,JRS,
	JSA,JSD,JSH,JSI,JSM,JSO,JSR,JSS,JST,JSU,JSY,JTO,JTR,JTY,JUA,JUB,JUI,JUJ,JUL,JUM,JUN,JUO,JUR,JUT,JUV,JUZ,JVA,JVI,JVL,JWA,JXN,JYV,JZH,KAA,KAB,KAC,KAD,KAE,KAF,KAG,KAI,KAJ,KAK,KAL,KAM,KAN,KAO,KAP,KAQ,KAR,KAS,KAT,KAU,KAV,KAW,KAX,KAY,KAZ,KBA,KBB,KBC,KBD,KBE,KBF,KBG,KBH,KBI,KBJ,KBK,KBL,KBM,KBN,KBO,KBQ,KBR,KBS,KBT,KBU,KBV,KBX,KBY,KBZ,KCA,KCB,KCC,KCE,KCH,KCI,KCK,KCL,KCM,KCN,KCP,KCR,KCS,KCU,KCZ,KDA,KDB,KDC,
	KDD,KDE,KDG,KDH,KDI,KDJ,KDL,KDN,KDP,KDR,KDS,KDU,KDV,KEA,KEB,KEC,KED,KEE,KEG,KEH,KEI,KEJ,KEK,KEL,KEM,KEN,KEO,KEP,KEQ,KER,KES,KET,KEU,KEV,KEX,KEY,KFA,KFG,KFP,KGA,KGB,KGC,KGD,KGF,KGG,KGH,KGI,KGJ,KGK,KGL,KGM,KGN,KGO,KGR,KGS,KGU,KGW,KGX,KGY,KGZ,KHA,KHC,KHE,KHG,KHH,KHI,KHJ,KHK,KHL,KHM,KHN,KHO,KHR,KHS,KHT,KHU,KHV,KHW,KIA,KIB,KIC,KID,KIE,KIF,KIG,KIH,KIJ,KIK,KIL,KIM,KIN,KIO,KIQ,KIR,KIS,KIT,KIU,KIV,KIW,KIY,
	KIZ,KJA,KJK,KJP,KJU,KKA,KKB,KKC,KKD,KKE,KKF,KKG,KKH,KKI,KKJ,KKK,KKL,KKM,KKN,KKO,KKP,KKR,KKT,KKU,KKW,KKX,KKY,KKZ,KLB,KLC,KLD,KLE,KLF,KLG,KLH,KLI,KLJ,KLK,KLL,KLN,KLO,KLP,KLQ,KLR,KLS,KLT,KLU,KLV,KLW,KLX,KLY,KLZ,KMA,KMB,KMD,KME,KMF,KMG,KMH,KMI,KMJ,KMK,KML,KMM,KMN,KMO,KMP,KMQ,KMR,KMS,KMT,KMU,KMV,KMW,KMX,KMY,KMZ,KNA,KNB,KNC,KND,KNE,KNF,KNG,KNH,KNI,KNJ,KNK,KNL,KNM,KNN,KNO,KNQ,KNR,KNS,KNT,KNU,KNW,KNX,KNY,
	KNZ,KOA,KOB,KOC,KOD,KOE,KOF,KOG,KOH,KOI,KOJ,KOK,KOL,KOM,KON,KOO,KOP,KOR,KOS,KOT,KOU,KOV,KOW,KOX,KOY,KOZ,KPA,KPB,KPC,KPD,KPE,KPG,KPH,KPI,KPK,KPM,KPN,KPO,KPP,KPR,KPS,KPT,KPV,KPY,KQA,KQB,KQL,KRA,KRB,KRC,KRD,KRE,KRF,KRG,KRI,KRJ,KRK,KRL,KRM,KRN,KRO,KRP,KRQ,KRR,KRS,KRT,KRU,KRV,KRW,KRX,KRY,KRZ,KSA,KSB,KSC,KSD,KSE,KSF,KSG,KSH,KSI,KSJ,KSK,KSL,KSM,KSN,KSO,KSP,KSQ,KSR,KSS,KST,KSU,KSV,KSW,KSX,KSY,KSZ,KTA,KTB,
	KTC,KTD,KTE,KTF,KTG,KTH,KTI,KTK,KTL,KTM,KTN,KTO,KTQ,KTR,KTS,KTT,KTU,KTV,KTW,KTX,KUA,KUB,KUC,KUD,KUE,KUF,KUG,KUH,KUI,KUJ,KUK,KUL,KUM,KUN,KUO,KUP,KUQ,KUR,KUS,KUT,KUU,KUV,KUW,KUZ,KVA,KVB,KVC,KVD,KVE,KVG,KVK,KVL,KVU,KVX,KWA,KWB,KWD,KWE,KWF,KWG,KWH,KWI,KWJ,KWK,KWL,KWM,KWN,KWO,KWP,KWR,KWS,KWT,KWU,KWV,KWX,KWY,KWZ,KXA,KXE,KXF,KXK,KXR,KYA,KYB,KYD,KYE,KYF,KYI,KYK,KYL,KYN,KYP,KYS,KYT,KYU,KYX,KYZ,KZB,KZC,KZD,
	KZF,KZH,KZI,KZK,KZN,KZS,LAA,LAB,LAC,LAD,LAE,LAF,LAG,LAH,LAI,LAJ,LAK,LAL,LAM,LAN,LAO,LAP,LAQ,LAR,LAS,LAT,LAU,LAV,LAW,LAX,LAY,LAZ,LBA,LBB,LBC,LBD,LBE,LBF,LBI,LBJ,LBK,LBL,LBM,LBN,LBO,LBQ,LBR,LBS,LBT,LBU,LBV,LBW,LBX,LBY,LCA,LCB,LCC,LCD,LCE,LCG,LCH,LCI,LCJ,LCL,LCM,LCN,LCO,LCR,LCS,LCV,LDA,LDB,LDC,LDE,LDH,LDI,LDJ,LDK,LDM,LDN,LDO,LDR,LDU,LDV,LDW,LDX,LDY,LDZ,LEA,LEB,LED,LEE,LEF,LEG,LEH,LEI,LEJ,LEK,LEL,LEM,
	LEO,LEP,LEQ,LER,LES,LET,LEU,LEV,LEW,LEX,LEY,LEZ,LFN,LFO,LFP,LFR,LFT,LFW,LGB,LGC,LGD,LGG,LGH,LGI,LGK,LGL,LGM,LGN,LGO,LGP,LGQ,LGR,LGS,LGT,LGU,LGX,LGY,LGZ,LHA,LHB,LHE,LHG,LHI,LHK,LHN,LHP,LHS,LHV,LHW,LIA,LIB,LIC,LID,LIE,LIF,LIG,LIH,LII,LIJ,LIK,LIL,LIM,LIO,LIP,LIQ,LIR,LIS,LIT,LIV,LIW,LIX,LIY,LIZ,LJA,LJG,LJN,LJU,LKA,LKB,LKC,LKD,LKK,LKL,LKN,LKO,LKP,LKR,LKS,LKT,LKU,LKV,LKY,LKZ,LLA,LLE,LLG,LLH,LLI,LLL,LLM,
	LLN,LLP,LLS,LLW,LLX,LLY,LMA,LMB,LMC,LMD,LME,LMG,LMH,LMI,LML,LMM,LMN,LMO,LMP,LMQ,LMR,LMS,LMT,LMX,LMY,LMZ,LNB,LNC,LND,LNE,LNF,LNG,LNH,LNI,LNK,LNM,LNN,LNO,LNP,LNQ,LNR,LNS,LNV,LNX,LNY,LNZ,LOA,LOB,LOC,LOD,LOE,LOF,LOG,LOH,LOK,LOL,LOM,LON,LOO,LOQ,LOS,LOT,LOV,LOW,LOY,LOZ,LPA,LPB,LPC,LPD,LPE,LPG,LPH,LPI,LPJ,LPK,LPL,LPM,LPN,LPO,LPP,LPQ,LPS,LPT,LPU,LPW,LPX,LPY,LQK,LQM,LQN,LRA,LRB,LRC,LRD,LRE,LRF,LRG,LRH,LRI,
	LRJ,LRK,LRL,LRM,LRO,LRQ,LRS,LRT,LRU,LRV,LSA,LSB,LSC,LSE,LSH,LSJ,LSK,LSL,LSM,LSN,LSO,LSP,LSQ,LSR,LSS,LST,LSU,LSW,LSX,LSY,LSZ,LTA,LTB,LTC,LTD,LTF,LTG,LTH,LTI,LTK,LTL,LTM,LTO,LTP,LTQ,LTR,LTS,LTT,LTV,LTW,LUA,LUB,LUC,LUD,LUE,LUG,LUH,LUI,LUJ,LUL,LUM,LUN,LUO,LUP,LUQ,LUR,LUS,LUT,LUU,LUV,LUW,LUX,LUY,LUZ,LVA,LVB,LVD,LVI,LVK,LVL,LVM,LVO,LVP,LVS,LWA,LWB,LWC,LWE,LWH,LWI,LWL,LWM,LWN,LWO,LWR,LWS,LWT,LWV,LWY,LXA,
	LXG,LXI,LXN,LXR,LXS,LXU,LXV,LYA,LYB,LYC,LYE,LYG,LYH,LYI,LYK,LYO,LYP,LYR,LYS,LYT,LYU,LYX,LZA,LZC,LZH,LZI,LZO,LZR;
	
	public static Set<String> toStringSet () {
		final Set<String>  set = new HashSet<String>();
		for (CityCodeGL cc : values ()){
			set.add(cc.toString());
		}
		return set ;
	}
}
