/*
 * Copyright 2015 Loic Merckel
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package lh.api.showcase.shared;

import java.util.HashSet;
import java.util.Set;

public enum CityCodeMR {
	
	MAA,MAB,MAD,MAE,MAF,MAG,MAH,MAI,MAJ,MAK,MAL,MAM,MAN,MAO,MAP,MAQ,MAR,MAS,MAT,MAU,MAV,MAW,MAX,MAY,MAZ,MBA,MBB,MBC,MBD,MBE,MBF,MBG,MBH,MBI,MBJ,MBK,MBL,MBM,MBN,MBO,MBP,MBQ,MBR,MBS,MBT,MBU,MBV,MBW,MBX,MBY,MBZ,MCA,MCB,MCD,MCE,MCG,MCH,MCJ,MCK,MCL,MCM,MCN,MCP,MCQ,MCR,MCS,MCT,MCU,MCV,MCW,MCX,MCY,
	MCZ,MDB,MDC,MDE,MDF,MDG,MDH,MDI,MDJ,MDK,MDL,MDM,MDN,MDO,MDP,MDQ,MDR,MDS,MDU,MDV,MDX,MDY,MDZ,MEA,MEC,MED,MEE,MEF,MEG,MEH,MEI,MEJ,MEK,MEL,MEM,MEN,MEO,MEP,MEQ,MES,MET,MEU,MEV,MEW,MEX,MEY,MEZ,MFA,MFB,MFC,MFD,MFE,MFF,MFG,MFI,MFJ,MFL,MFM,MFN,MFO,MFP,MFQ,MFR,MFS,MFU,MFV,MFX,MFY,MGA,MGB,MGC,MGD,MGF,MGG,MGH,MGI,MGJ,MGK,MGL,MGM,MGN,MGO,MGP,MGQ,MGR,MGS,MGT,MGU,MGV,MGW,MGX,MGZ,MHA,MHC,MHD,MHE,MHF,MHG,MHH,MHI,
	MHJ,MHK,MHL,MHM,MHN,MHO,MHQ,MHS,MHT,MHU,MHV,MHX,MHY,MHZ,MIA,MID,MIE,MIF,MIG,MIH,MII,MIJ,MIK,MIL,MIM,MIN,MIP,MIR,MIS,MIT,MIU,MIV,MIW,MIX,MIY,MIZ,MJA,MJB,MJC,MJD,MJE,MJF,MJG,MJH,MJI,MJJ,MJK,MJL,MJM,MJN,MJP,MJQ,MJR,MJS,MJT,MJU,MJV,MJY,MJZ,MKA,MKB,MKC,MKD,MKE,MKG,MKH,MKI,MKJ,MKK,MKL,MKM,MKN,MKO,MKP,MKQ,MKR,MKS,MKT,MKU,MKV,MKW,MKX,MKY,MKZ,MLA,MLB,MLC,MLD,MLE,MLF,MLG,MLH,MLI,MLJ,MLK,MLL,MLM,MLN,MLO,MLP,
	MLQ,MLR,MLS,MLT,MLU,MLV,MLW,MLX,MLY,MLZ,MMA,MMB,MMC,MMD,MME,MMF,MMG,MMH,MMI,MMJ,MMK,MML,MMM,MMN,MMO,MMP,MMQ,MMS,MMU,MMV,MMW,MMY,MMZ,MNA,MNB,MNC,MND,MNE,MNF,MNG,MNH,MNI,MNJ,MNK,MNL,MNM,MNN,MNO,MNP,MNQ,MNR,MNS,MNT,MNU,MNV,MNW,MNX,MNY,MNZ,MOA,MOB,MOC,MOD,MOE,MOF,MOG,MOH,MOI,MOJ,MOK,MOL,MOM,MON,MOO,MOP,MOQ,MOR,MOS,MOT,MOU,MOV,MOW,MOX,MOY,MOZ,MPA,MPC,MPD,MPE,MPF,MPG,MPH,MPI,MPJ,MPK,MPL,MPM,MPN,MPO,MPP,
	MPQ,MPR,MPS,MPT,MPU,MPV,MPW,MPX,MPY,MPZ,MQA,MQB,MQC,MQD,MQE,MQF,MQH,MQI,MQL,MQM,MQN,MQQ,MQR,MQS,MQT,MQU,MQW,MQX,MQY,MRA,MRB,MRC,MRD,MRE,MRF,MRG,MRH,MRJ,MRK,MRL,MRM,MRN,MRO,MRP,MRQ,MRR,MRS,MRT,MRU,MRV,MRW,MRX,MRY,MRZ,MSA,MSC,MSD,MSE,MSF,MSG,MSH,MSI,MSJ,MSK,MSL,MSM,MSN,MSO,MSP,MSQ,MSR,MSS,MST,MSU,MSV,MSW,MSX,MSY,MSZ,MTA,MTB,MTD,MTE,MTF,MTG,MTH,MTI,MTJ,MTK,MTL,MTM,MTO,MTP,MTQ,MTR,MTS,MTT,MTU,MTV,MTW,
	MTY,MTZ,MUA,MUB,MUC,MUD,MUE,MUF,MUG,MUH,MUI,MUJ,MUK,MUM,MUN,MUO,MUP,MUQ,MUR,MUS,MUT,MUU,MUW,MUX,MUZ,MVA,MVB,MVC,MVD,MVE,MVF,MVG,MVH,MVI,MVJ,MVK,MVL,MVM,MVN,MVO,MVP,MVQ,MVR,MVS,MVT,MVU,MVV,MVW,MVX,MVY,MVZ,MWA,MWB,MWD,MWE,MWF,MWG,MWH,MWI,MWJ,MWK,MWL,MWM,MWN,MWO,MWQ,MWR,MWS,MWT,MWU,MWX,MWY,MWZ,MXA,MXB,MXC,MXD,MXE,MXG,MXH,MXI,MXJ,MXK,MXL,MXM,MXN,MXO,MXQ,MXR,MXS,MXT,MXU,MXV,MXW,MXX,MXY,MXZ,MYA,MYB,MYC,
	MYD,MYE,MYG,MYH,MYI,MYJ,MYK,MYL,MYM,MYN,MYO,MYP,MYQ,MYR,MYS,MYT,MYU,MYV,MYW,MYX,MYY,MYZ,MZA,MZB,MZC,MZD,MZE,MZF,MZG,MZH,MZI,MZJ,MZK,MZL,MZN,MZO,MZP,MZQ,MZR,MZS,MZT,MZU,MZV,MZX,MZY,MZZ,NAA,NAC,NAD,NAE,NAF,NAG,NAH,NAI,NAK,NAL,NAM,NAN,NAO,NAP,NAQ,NAR,NAS,NAT,NAU,NAV,NAW,NAX,NBA,NBB,NBC,NBE,NBH,NBL,NBO,NBR,NBU,NBV,NBX,NCA,NCE,NCG,NCH,NCI,NCL,NCN,NCO,NCP,NCR,NCS,NCT,NCU,NCY,NDA,NDB,NDC,NDD,NDE,NDG,NDI,
	NDJ,NDK,NDL,NDM,NDN,NDR,NDS,NDU,NDV,NDY,NDZ,NEA,NEC,NEF,NEG,NEJ,NEK,NEL,NEN,NER,NEU,NEV,NFG,NFL,NFO,NGA,NGB,NGD,NGE,NGI,NGL,NGN,NGO,NGR,NGS,NGV,NGX,NGZ,NHA,NHD,NHF,NHK,NHS,NHT,NHV,NHX,NIA,NIB,NIC,NIE,NIF,NIG,NIK,NIM,NIN,NIO,NIR,NIT,NIX,NJA,NJC,NKA,NKB,NKC,NKD,NKG,NKI,NKL,NKN,NKS,NKU,NKV,NKY,NLA,NLC,NLD,NLE,NLF,NLG,NLK,NLL,NLP,NLS,NLV,NMA,NMB,NMC,NME,NMG,NMN,NMP,NMR,NMS,NMT,NMU,NNA,NNB,NND,NNG,NNI,
	NNK,NNL,NNM,NNT,NNU,NNX,NNY,NOA,NOB,NOC,NOD,NOE,NOG,NOI,NOJ,NOK,NOL,NOM,NON,NOO,NOP,NOR,NOS,NOT,NOU,NOV,NOZ,NPE,NPG,NPH,NPL,NPO,NPP,NPT,NPU,NQI,NQL,NQN,NQT,NQU,NQY,NRA,NRB,NRC,NRD,NRE,NRG,NRI,NRK,NRL,NRM,NRQ,NRS,NRY,NSA,NSE,NSH,NSK,NSM,NSN,NSO,NSP,NST,NSV,NSX,NSY,NTA,NTB,NTC,NTD,NTE,NTG,NTI,NTJ,NTL,NTM,NTN,NTO,NTQ,NTT,NTU,NTX,NTY,NUB,NUC,NUD,NUE,NUG,NUH,NUI,NUK,NUL,NUP,NUQ,NUR,NUS,NUT,NUU,NUW,NUX,
	NVA,NVD,NVG,NVK,NVP,NVR,NVS,NVT,NVY,NWA,NWH,NWI,NWP,NWT,NXX,NYC,NYE,NYI,NYK,NYM,NYN,NYO,NYU,NZE,NZO,NZW,OAG,OAJ,OAK,OAM,OAN,OAX,OBA,OBC,OBD,OBE,OBF,OBI,OBK,OBM,OBN,OBO,OBS,OBU,OBX,OBY,OCA,OCC,OCE,OCF,OCH,OCI,OCJ,OCN,OCV,OCW,ODA,ODB,ODD,ODE,ODH,ODJ,ODL,ODM,ODN,ODR,ODS,ODW,ODY,OEA,OEC,OEL,OEM,OEO,OER,OES,OFI,OFJ,OFK,OFU,OGA,OGB,OGD,OGE,OGG,OGN,OGO,OGR,OGS,OGX,OGZ,OHA,OHD,OHI,OHO,OHR,OHT,OIC,OIM,OIR,
	OIT,OKA,OKB,OKC,OKE,OKF,OKG,OKH,OKI,OKJ,OKK,OKL,OKM,OKN,OKP,OKQ,OKR,OKS,OKT,OKU,OKY,OLA,OLB,OLD,OLE,OLF,OLH,OLI,OLJ,OLM,OLN,OLO,OLP,OLQ,OLS,OLU,OLV,OLY,OMA,OMB,OMC,OMD,OME,OMF,OMG,OMH,OMJ,OMK,OML,OMM,OMN,OMO,OMR,OMS,OMY,ONA,ONB,OND,ONE,ONG,ONH,ONI,ONJ,ONL,ONN,ONO,ONP,ONR,ONS,ONT,ONU,ONX,ONY,OOA,OOK,OOL,OOM,OOR,OOT,OPA,OPB,OPI,OPL,OPO,OPS,OPU,OPW,ORA,ORB,ORC,ORE,ORF,ORH,ORI,ORJ,ORK,ORL,ORM,ORN,ORO,
	ORP,ORQ,ORR,ORS,ORT,ORU,ORV,ORW,ORX,ORZ,OSA,OSB,OSC,OSD,OSE,OSG,OSH,OSI,OSK,OSL,OSM,OSN,OSP,OSR,OSS,OST,OSW,OSX,OSY,OSZ,OTA,OTC,OTD,OTG,OTH,OTI,OTL,OTM,OTN,OTO,OTR,OTS,OTU,OTY,OTZ,OUA,OUD,OUE,OUG,OUH,OUI,OUK,OUL,OUM,OUN,OUR,OUS,OUT,OUU,OUZ,OVA,OVB,OVD,OVE,OVL,OWA,OWB,OWD,OWE,OWK,OXB,OXC,OXD,OXF,OXO,OXR,OXY,OYA,OYE,OYG,OYK,OYL,OYN,OYO,OYP,OYS,OZA,OZC,OZH,OZP,OZZ,PAA,PAB,PAD,PAE,PAF,PAG,PAH,PAI,PAJ,
	PAK,PAL,PAN,PAO,PAP,PAQ,PAR,PAS,PAT,PAU,PAV,PAW,PAX,PAY,PAZ,PBB,PBC,PBD,PBE,PBF,PBH,PBI,PBJ,PBK,PBL,PBM,PBN,PBO,PBQ,PBR,PBS,PBU,PBW,PBZ,PCA,PCB,PCC,PCD,PCE,PCG,PCH,PCK,PCL,PCM,PCN,PCO,PCP,PCR,PCS,PCT,PCU,PCV,PDA,PDB,PDC,PDE,PDF,PDG,PDI,PDL,PDN,PDO,PDP,PDR,PDS,PDT,PDU,PDV,PDX,PDZ,PEA,PEB,PEC,PEE,PEG,PEH,PEI,PEL,PEM,PEN,PEP,PEQ,PER,PES,PET,PEU,PEV,PEW,PEX,PEY,PEZ,PFA,PFB,PFC,PFD,PFJ,PFN,PFO,PFR,PGA,
	PGB,PGC,PGD,PGE,PGF,PGG,PGH,PGI,PGK,PGL,PGM,PGN,PGO,PGP,PGR,PGS,PGV,PGX,PGZ,PHA,PHB,PHC,PHD,PHE,PHF,PHH,PHI,PHJ,PHK,PHL,PHM,PHN,PHO,PHP,PHR,PHS,PHT,PHU,PHW,PHX,PHZ,PIA,PIC,PIE,PIG,PIH,PIL,PIM,PIN,PIO,PIP,PIQ,PIR,PIS,PIT,PIU,PIV,PIW,PIX,PIZ,PJB,PJC,PJG,PJM,PJS,PJZ,PKA,PKB,PKC,PKD,PKE,PKF,PKG,PKH,PKK,PKL,PKM,PKN,PKO,PKP,PKR,PKS,PKT,PKU,PKV,PKW,PKY,PKZ,PLA,PLB,PLC,PLD,PLE,PLF,PLG,PLH,PLI,PLJ,PLK,PLL,
	PLM,PLN,PLO,PLP,PLQ,PLR,PLS,PLT,PLV,PLW,PLX,PLY,PLZ,PMA,PMB,PMC,PMD,PME,PMF,PMG,PMH,PMI,PMK,PML,PMM,PMN,PMO,PMP,PMQ,PMR,PMS,PMT,PMU,PMV,PMW,PMX,PMY,PMZ,PNA,PNB,PNC,PND,PNF,PNG,PNH,PNI,PNK,PNL,PNN,PNO,PNP,PNQ,PNR,PNS,PNT,PNU,PNV,PNX,PNY,PNZ,POA,POC,POD,POE,POF,POG,POH,POI,POL,POM,PON,POO,POP,POQ,POR,POS,POT,POU,POV,POW,POX,POY,POZ,PPA,PPB,PPC,PPE,PPF,PPG,PPH,PPI,PPJ,PPK,PPL,PPM,PPN,PPO,PPP,PPQ,PPR,
	PPS,PPT,PPU,PPV,PPW,PPY,PPZ,PQC,PQI,PQM,PQQ,PQS,PRA,PRB,PRC,PRD,PRE,PRF,PRG,PRH,PRI,PRJ,PRK,PRL,PRM,PRN,PRO,PRP,PRQ,PRR,PRS,PRT,PRU,PRV,PRW,PRX,PRY,PRZ,PSA,PSB,PSC,PSD,PSE,PSF,PSG,PSH,PSI,PSJ,PSK,PSL,PSN,PSO,PSP,PSR,PSS,PST,PSU,PSV,PSW,PSX,PSY,PSZ,PTA,PTB,PTC,PTD,PTE,PTF,PTG,PTH,PTI,PTJ,PTK,PTL,PTM,PTN,PTO,PTP,PTQ,PTR,PTS,PTT,PTU,PTV,PTW,PTX,PTY,PTZ,PUA,PUB,PUC,PUD,PUE,PUF,PUG,PUH,PUI,PUJ,PUK,PUL,
	PUM,PUN,PUO,PUP,PUQ,PUR,PUS,PUT,PUU,PUV,PUW,PUX,PUY,PUZ,PVA,PVC,PVD,PVE,PVF,PVH,PVI,PVK,PVN,PVO,PVR,PVS,PVU,PVW,PVX,PVY,PVZ,PWD,PWE,PWI,PWL,PWM,PWN,PWO,PWQ,PWR,PWT,PXL,PXM,PXO,PXU,PYA,PYB,PYC,PYE,PYH,PYJ,PYL,PYM,PYN,PYO,PYR,PYV,PYX,PZA,PZB,PZE,PZH,PZL,PZO,PZU,PZY, 
	QAP,QBC,QFB,QGJ,QJU,QJY,QMZ,QNF,QNI,QPA,QRO,QRW,QSR,QUF,QWU,QXZ,QYG,RAA,RAB,RAC,RAE,RAG,RAH,RAI,RAJ,RAK,RAL,RAM,RAN,RAO,RAP,RAQ,RAR,RAS,
	RAT,RAU,RAV,RAW,RAX,RAY,RAZ,RBA,RBB,RBC,RBF,RBG,RBH,RBI,RBJ,RBK,RBL,RBM,RBN,RBO,RBP,RBQ,RBR,RBS,RBT,RBU,RBW,RBY,RCB,RCE,RCH,RCK,RCL,RCM,RCN,RCO,RCQ,RCR,RCS,RCT,RCU,RCY,RDA,RDB,RDC,RDD,RDE,RDG,RDM,RDR,RDS,RDT,RDU,RDV,RDZ,REA,REC,RED,REG,REH,REI,REK,REL,REN,REO,REP,RES,RET,REU,REW,REX,REY,RFA,RFD,RFG,RFK,RFN,RFP,RFR,RGA,RGE,RGH,RGI,RGL,RGN,RGR,RGT,RHA,RHD,RHE,RHG,RHI,RHL,RHO,RHP,RIA,RIB,RIC,RID,RIE,
	RIF,RIG,RIJ,RIK,RIL,RIM,RIN,RIO,RIS,RIT,RIW,RIX,RIY,RIZ,RJA,RJB,RJH,RJI,RJK,RKC,RKD,RKH,RKI,RKO,RKP,RKR,RKS,RKT,RKU,RKW,RKY,RLA,RLD,RLG,RLP,RLT,RLU,RMA,RMB,RMD,RME,RMF,RMG,RMI,RMK,RMN,RMP,RMS,RNB,RNC,RNE,RNG,RNH,RNI,RNJ,RNL,RNN,RNO,RNP,RNR,RNS,RNT,RNU,RNZ,ROA,ROC,ROD,ROG,ROH,ROK,ROL,ROM,RON,ROO,ROP,ROR,ROS,ROT,ROU,ROV,ROW,ROX,ROY,RPA,RPB,RPM,RPN,RPR,RPV,RPX,RRE,RRG,RRI,RRK,RRL,RRM,RRN,RRO,RRS,RRV,
	RSA,RSB,RSD,RSG,RSI,RSJ,RSK,RSL,RSN,RSP,RSS,RST,RSU,RSX,RTA,RTB,RTC,RTD,RTE,RTG,RTI,RTL,RTM,RTN,RTP,RTS,RTW,RTY,RUA,RUF,RUG,RUH,RUI,RUK,RUM,RUN,RUP,RUR,RUS,RUT,RUU,RUV,RUY,RVA,RVC,RVD,RVE,RVK,RVN,RVO,RVR,RVY,RWB,RWF,RWI,RWL,RWN,RXA,RXS,RYB,RYK,RYN,RYO,RZA,RZE,RZN,RZR,RZZ;

	public static Set<String> toStringSet () {
		final Set<String>  set = new HashSet<String>();
		for (CityCodeMR cc : values ()){
			set.add(cc.toString());
		}
		return set ;
	}
}
